<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SWQA-1" failures="1" tests="1" name="EscortManagementTest" time="4.768" errors="0" timestamp="2024-05-23T10:47:54 BST">
  <testcase classname="sm.tests.EscortManagementTest" name="signIn" time="1.307">
    <failure type="java.lang.AssertionError" message="expected [An unexpected error occurred on the server. Please try again later.] but found [No account with login id sri.mettu@multitone.com]">
      <![CDATA[java.lang.AssertionError: expected [An unexpected error occurred on the server. Please try again later.] but found [No account with login id sri.mettu@multitone.com]
at sm.tests.EscortManagementTest.signIn(EscortManagementTest.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn -->
</testsuite> <!-- EscortManagementTest -->
